# Enable all methods on nodes.
# You must install Hal and Basic_auth modules for this to work. Also, if you are
# going to use Basic_auth in a production environment then you should consider
# setting up SSL.
# There are alternatives to Basic_auth in contrib such as OAuth module.
resources:
  entity:node:
    GET:
      supported_formats:
        - json
      supported_auth:
        - cookie
    POST:
      supported_formats:
        - json
      supported_auth:
        - cookie
    PATCH:
      supported_formats:
        - json
      supported_auth:
        - cookie
    DELETE:
      supported_formats:
        - json
      supported_auth:
        - cookie

# Multiple formats and multiple authentication providers can be defined for a
# resource:
#
# resources:
#   entity:node:
#     GET:
#       supported_formats:
#         - json
#         - json
#         - xml
#       supported_auth:
#         - cookie
#         - cookie
#
# json is the only format supported for POST and PATCH methods.
#
# The full documentation is located at
# https://www.drupal.org/documentation/modules/rest.

# Set the domain for REST type and relation links.
# If left blank, the site's domain will be used.
link_domain: ~